import React from 'react';
import { useQuery } from '@tanstack/react-query';
import { fetchScreenshots } from '../api/client';
import { LoadingSkeleton } from '../components/ui/LoadingSkeleton';
import { EmptyState } from '../components/ui/EmptyState';
import { Badge } from '../components/ui/Badge';
import { Sparkles, Tag, CheckCircle2, RefreshCw } from 'lucide-react';

export const AIInsightsPage: React.FC = () => {
  const { data, isLoading, refetch } = useQuery({
    queryKey: ['ai-insights-list'],
    queryFn: () => fetchScreenshots({ limit: 50 }),
    refetchInterval: 10000,
  });

  const screenshotsWithAnalysis = data?.data.filter((s) => s.analysis) || [];

  if (isLoading) return <LoadingSkeleton rows={6} />;

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-white tracking-tight">AI Vision Insights</h2>
          <p className="text-xs text-slate-400">Semantic evaluation generated by Google Gemini 2.5 Flash Multimodal Vision model</p>
        </div>
        <button
          onClick={() => refetch()}
          className="inline-flex items-center space-x-2 px-3 py-1.5 rounded-xl bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-xs font-semibold hover:bg-cyan-500/20 transition"
        >
          <RefreshCw className="w-3.5 h-3.5" />
          <span>Refresh Insights</span>
        </button>
      </div>

      {screenshotsWithAnalysis.length === 0 ? (
        <EmptyState
          title="No AI Vision Analyses Generated Yet"
          description="Capture browser activity or ensure GEMINI_API_KEY / Mock Vision Provider is active on the Express server."
          icon={Sparkles}
        />
      ) : (
        <div className="space-y-4">
          {screenshotsWithAnalysis.map((item) => {
            const a = item.analysis!;
            return (
              <div key={item.screenshotId} className="p-6 rounded-2xl glass-card space-y-4 border border-cyan-500/20">
                <div className="flex items-center justify-between flex-wrap gap-2">
                  <div className="flex items-center space-x-3">
                    <div className="w-8 h-8 rounded-xl bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 flex items-center justify-center">
                      <Sparkles className="w-4 h-4" />
                    </div>
                    <div>
                      <h4 className="text-sm font-bold text-white truncate max-w-md">{item.title || item.url}</h4>
                      <p className="text-[11px] text-slate-400 font-mono">{item.url}</p>
                    </div>
                  </div>

                  <div className="flex items-center space-x-3">
                    <Badge label={a.category} variant="cyan" />
                    <div className="flex items-center space-x-1.5 px-3 py-1 rounded-full bg-slate-900 border border-slate-800 text-xs font-medium text-emerald-400">
                      <CheckCircle2 className="w-3.5 h-3.5" />
                      <span>{Math.round(a.confidence * 100)}% Confidence</span>
                    </div>
                  </div>
                </div>

                {/* AI Summary */}
                <p className="text-sm text-slate-200 leading-relaxed font-medium bg-slate-900/40 p-4 rounded-xl border border-slate-800/60">
                  {a.summary}
                </p>

                {/* Productivity Gauge */}
                <div className="space-y-2">
                  <div className="flex justify-between text-xs font-semibold">
                    <span className="text-slate-400">Productivity Score Evaluation</span>
                    <span className="text-cyan-400 font-mono font-bold">{a.productivityScore} / 100</span>
                  </div>
                  <div className="h-2.5 bg-slate-900 rounded-full overflow-hidden p-0.5 border border-slate-800">
                    <div
                      className="h-full bg-gradient-to-r from-cyan-500 via-indigo-500 to-emerald-400 rounded-full transition-all duration-500"
                      style={{ width: `${a.productivityScore}%` }}
                    />
                  </div>
                </div>

                {/* Tags and Metadata */}
                <div className="flex items-center justify-between pt-2 border-t border-slate-800/80 text-xs">
                  <div className="flex items-center space-x-2 flex-wrap gap-y-1">
                    <Tag className="w-3.5 h-3.5 text-slate-500 shrink-0" />
                    {a.entities && a.entities.map((tag, idx) => (
                      <span key={idx} className="bg-slate-900 text-slate-300 px-2 py-0.5 rounded-md font-mono text-[11px] border border-slate-800">
                        #{tag}
                      </span>
                    ))}
                  </div>

                  <div className="text-slate-500 font-mono text-[11px]">
                    Analyzed at: {new Date(a.analyzedAt).toLocaleTimeString()} ({a.model})
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
